export const tags = [
  'technology',
  'science',
  'health',
  'sports',
  'news',
  'education',
  'lifestyle',
  'travel',
  'food',
  'fashion',
  'entertainment',
  'business',
  'finance',
  'history',
  'culture',
  'politics',
  'environment',
  'art',
  'design',
  'architecture',
  'music',
  'photography',
  'gaming',
  'DIY',
  'parenting',
  'fitness',
  'personal development',
  'programming',
  'AI',
  'machine learning',
  'data science',
  'software',
  'hardware',
  'cloud computing',
  'big data',
  'robotics',
  'cybersecurity',
  'blockchain',
  'coding',
  'gadgets',
  'electronics',
  'space',
  'astronomy',
  'biology',
  'physics',
  'chemistry',
  'mathematics',
  'quantum computing',
  'nanotechnology',
  'biotech',
  'fitness',
  'wellness',
  'mental health',
  'yoga',
  'meditation',
  'nutrition',
  'workouts',
  'weight loss',
  'bodybuilding',
  'sports medicine',
  'running',
  'cycling',
  'hiking',
  'swimming',
  'football',
  'basketball',
  'tennis',
  'golf',
  'athletics',
  'martial arts',
  'surfing',
  'snowboarding',
  'skiing',
  'boxing',
  'destinations',
  'adventure',
  'backpacking',
  'road trip',
  'camping',
  'beaches',
  'mountains',
  'cultural heritage',
  'festivals',
  'local cuisine',
  'artifacts',
  'city guide',
  'tours',
  'nature',
  'wildlife',
  'historical sites',
  'languages',
  'customs',
  'traditional clothing',
  'religion',
  'museums',
  'photography tips',
  'painting',
  'sculpture',
  'digital art',
  'graphic design',
  'illustration',
  'street art',
  'modern art',
  'abstract art',
  'classical art',
  'architecture',
  'interior design',
  'product design',
  'web design',
  'UX/UI',
  'animation',
  'photography',
  'film',
  'videography',
  '3D modeling',
  'ceramics',
  'fine art',
  'recipes',
  'baking',
  'cocktails',
  'wine',
  'coffee',
  'tea',
  'vegan',
  'vegetarian',
  'gluten-free',
  'paleo',
  'keto',
  'meal prep',
  'street food',
  'fine dining',
  'food trends',
  'nutrition facts',
  'organic',
  'local food',
  'food photography',
  'desserts',
  'cooking tips',
  'ethnic cuisine',
  'healthy eating',
  'grilling',
  'investing',
  'stocks',
  'cryptocurrency',
  'startup',
  'entrepreneurship',
  'marketing',
  'branding',
  'e-commerce',
  'real estate',
  'personal finance',
  'saving money',
  'retirement',
  'loans',
  'budgeting',
  'insurance',
  'taxes',
  'economics',
  'business news',
  'small business',
  'productivity',
  'networking',
  'freelancing',
  'side hustle',
  'career advice',
  'job search',
  'remote work',
  'self-care',
  'mindfulness',
  'goal setting',
  'motivation',
  'time management',
  'productivity tips',
  'confidence',
  'relationships',
  'happiness',
  'journaling',
  'life coaching',
  'self-esteem',
  'emotional intelligence',
  'communication skills',
  'leadership',
  'creativity',
  'work-life balance',
  'mindset',
  'mental clarity',
  'stress management',
  'meditation practices',
  'habit building',
  'success tips',
  'global issues',
  'human rights',
  'social justice',
  'law',
  'democracy',
  'elections',
  'public policy',
  'gender equality',
  'environmental policy',
  'immigration',
  'activism',
  'community',
  'social movements',
  'civil rights',
  'freedom of speech',
  'diplomacy',
  'international relations',
  'urbanization',
  'healthcare',
  'education reform',
  'climate action',
  'youth activism',
  'voting rights',
  'poverty alleviation',
  'sustainability',
  'wildlife conservation',
  'renewable energy',
  'climate change',
  'recycling',
  'zero waste',
  'plastic-free',
  'ocean cleanup',
  'forestation',
  'biodiversity',
  'eco-friendly',
  'organic farming',
  'pollution',
  'clean energy',
  'animal rights',
  'carbon footprint',
  'green living',
  'natural resources',
  'alternative energy',
  'solar power',
  'wind energy',
  'environmental activism',
  'movies',
  'TV shows',
  'comics',
  'graphic novels',
  'board games',
  'puzzles',
  'video games',
  'gaming culture',
  'comedy',
  'stand-up',
  'cartoons',
  'anime',
  'manga',
  'cosplay',
  'magic tricks',
  'theater',
  'musicals',
  'concerts',
  'festivals',
  'street performances',
  'talent shows',
  'pop culture',
  'celebrity news',
  'fan art',
  'fashion trends',
  'streetwear',
  'vintage fashion',
  'DIY fashion',
  'minimalism',
  'skincare',
  'makeup',
  'hairstyles',
  'accessories',
  'sustainable fashion',
  'luxury brands',
  'second-hand',
  'outfit ideas',
  'personal style',
  'capsule wardrobe',
  'seasonal fashion',
  'runway',
  'red carpet',
  'fashion week',
  'body positivity',
  'beauty hacks',
  'grooming tips',
  'eco-friendly beauty',
  'ethical fashion',
  'learning',
  'online courses',
  'certifications',
  'higher education',
  'scholarships',
  'career planning',
  'job interviews',
  'resume tips',
  'internships',
  'networking',
  'soft skills',
  'hard skills',
  'career development',
  'workplace culture',
  'mentorship',
  'leadership skills',
  'technical skills',
  'creative skills',
  'work ethics',
  'teamwork',
  'professional growth',
  'life skills',
  'academic research',
  'volunteering',
  'motorsport',
  'luxury lifestyle',
  'urban exploration',
  'minimalist living',
  'home decor',
  'financial freedom',
  'digital marketing',
  'cryptocurrency trading',
  'app development',
  'eco-tourism',
  'coding bootcamps',
  'virtual reality',
  'social media tips',
  'pet care',
  'mental resilience',
  'startup life',
  'storytelling',
  'user experience',
  'backyard gardening',
  'digital detox',
  'self-improvement',
  'cultural exchange',
  'urban farming',
  'space exploration',
  'artificial intelligence ethics',
  'online security',
  'green energy',
  'smart home',
  'biohacking',
  'digital nomad',
  'tiny houses',
  'van life',
];
